routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function() {


    Route::group(['middleware' => ['role:Admin']], function () {

        Route::resource('roles','RoleController');
        Route::resource('users','UserController');
        Route::resource('products','ProductController');


        //Route::resource('administrator/supplier', 'AdministratorController\SupplierController',['names' => [
		//	'store' => 'administrator.supplier.store',
		//	'index' => 'administrator.supplier.index',
		//	'create' => 'administrator.supplier.create',
		//	'show' => 'administrator.supplier.show',
		//	'edit' => 'administrator.supplier.edit',
		//]]);
		//Route::post('administrator/supplier/update', 'AdministratorController\SupplierController@update')->name('administrator.supplier.update');
		//Route::get('administrator/supplier/destroy/{id}', 'AdministratorController\SupplierController@destroy');
		
		Route::get('solicitud', 'SolicitudController@index')->name('solicitud');
		Route::get('solicitud/partida', 'SolicitudController@partidas')->name('solicitud.partidas');
		Route::get('solicitud/word', 'SolicitudController@generadorWord')->name('solicitud.word');
		Route::get('solicitud/{id}', 'SolicitudController@porTipo');
		
		Route::post('solicitud/agregarSolicitud','SolicitudController@añadirSolicitud');
		//Route::resource('notasinternas','NotaInternaController',['names' => [
		//	'store' => 'notainterna.store',
		//	'index' => 'notainterna.index',
		//	'show' => 'notainterna.show',
		//]]);


		Route::resource('administrator/supplier','AdministratorController\SupplierController',['names' => [
			'store' => 'administrator.supplier.store',
			'index' => 'administrator.supplier.index',
			'show' => 'administrator.supplier.show',
		]]);

    	Route::post('administrator/supplier/addSupplier','AdministratorController\SupplierController@addSupplier');
    	Route::post('administrator/supplier/editSupplier','AdministratorController\SupplierController@editSupplier');
		Route::post('administrator/supplier/deleteSupplier','AdministratorController\SupplierController@deleteSupplier');

		

		
		Route::resource('administrator/typematerial','AdministratorController\TypeMaterialsController',['names' => [
			'store' => 'administrator.typematerial.store',
			'index' => 'administrator.typematerial.index',
			'show' => 'administrator.typematerial.show',
		]]);

    	Route::post('administrator/typematerial/addTypeMaterial','AdministratorController\TypeMaterialsController@addTypeMaterial');
    	Route::post('administrator/typematerial/editTypeMaterial','AdministratorController\TypeMaterialsController@editTypeMaterial');
		Route::post('administrator/typematerial/deleteTypeMaterial','AdministratorController\TypeMaterialsController@deleteTypeMaterial');
		
		//Route::resource('post','PostController');
    	//Route::POST('addPost','PostController@addPost');
    	//Route::POST('editPost','PostController@editPost');
    	//Route::POST('deletePost','PostController@deletePost');
    


	});

    
});

resources/views/layouts/partials/aside.blade.php
  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img class="round" width="160" height="160" avatar="{{ auth()->user()->name }}">
        </div>
        <div class="pull-left info">
          <p>{{ auth()->user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> En linea</a>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>

        <li ><a href="{{ route('solicitud') }}"><i class="fa fa-tasks"></i> <span>Documentos</span></a></li>
        <li class="treeview">

          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Administrador</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            
           
            <!--<li><a class="nav-link" href="{{ route('users.index') }}">Manage Users</a></li>-->
            <!--<li><a class="nav-link" href="{{ route('roles.index') }}">Manage Role</a></li>-->
            <!--<li><a class="nav-link" href="{{ route('products.index') }}">Manage Product</a></li>-->
            <li><a class="nav-link" href="{{ route('administrator.supplier.index') }}">Proveedores</a></li>
            <li><a class="nav-link" href="{{ route('administrator.typematerial.index') }}">Tipo Materiales</a></li>
  
          
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- =============================================== -->

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Unidad de Tecnologías de Información y Comunicación &copy; 2019 <a href="https://www.fonabosque.gob.bo/" target="_blank">FONABOSQUE</a>.</strong> Fondo Nacional de Desarrollo Forestal.
  </footer>

resources/views/layouts/partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="../../index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>CONTRATACIONES</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
      

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img class="round" width="19" height="19" avatar="{{ auth()->user()->name }}">
              <span class="hidden-xs">{{ auth()->user()->name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img class="round" width="160" height="160" class="user-image" avatar="{{ auth()->user()->name }}?>">
                <p>
                    {{ auth()->user()->name }}
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  
                  <form method="POST" action="{{ route('logout') }}">
                    {{ csrf_field() }}
                    <button class="btn btn-default btn-flat">Salir</button>
                  </form>

                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/layouts/partials/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>@yield('titulo', 'Contrataciones')| Sistema de Contrataciones</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="{{asset("bower_components/bootstrap/dist/css/bootstrap.min.css")}}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{{asset("bower_components/font-awesome/css/font-awesome.min.css")}}">
        <!-- iCheck for -->
        <link rel="stylesheet" href="{{asset("plugins/iCheck/all.css")}}">
        <!-- Ionicons -->
        <link rel="stylesheet" href="{{asset("bower_components/Ionicons/css/ionicons.min.css")}}">
        <!-- Theme style -->
        <link rel="stylesheet" href="{{asset("dist/css/AdminLTE.min.css")}}">
        <link rel="stylesheet" href="{{asset("dist/css/letteravatar.css")}}">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
            folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="{{asset("dist/css/skins/skin-green.css")}}">
        <!-- jQuery 3 -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
        <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script> 
        @yield('style')

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>
    <!-- ADD THE CLASS fixed TO GET A FIXED HEADER AND SIDEBAR LAYOUT -->
<!-- the fixed layout is not compatible with sidebar-mini -->
    <body class="hold-transition skin-green fixed sidebar-mini">
        @include("layouts/partials/header")
        @include("layouts/partials/aside")
        <!-- Site wrapper -->
        <div class="wrapper">
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <section class="content">

                    @yield('content')

                </section>
            </div>
            @include("layouts/partials/footer")
        </div>
       
        
            <!-- Bootstrap 3.3.7 -->
            <script src="{{asset("bower_components/bootstrap/dist/js/bootstrap.min.js")}}"></script>
            <!-- SlimScroll -->
            <script src="{{asset("bower_components/jquery-slimscroll/jquery.slimscroll.min.js")}}"></script>
            <!-- FastClick -->
            <script src="{{asset("bower_components/fastclick/lib/fastclick.js")}}"></script>
            <!-- iCheck 1.0.1 -->
            <script src="{{asset("plugins/iCheck/icheck.min.js")}}"></script>
            <!-- AdminLTE App -->
            <script src="{{asset("dist/js/adminlte.min.js")}}"></script>
            <script src="{{asset("dist/js/letteravatar.js")}}"></script>
            
         
            @yield('script')
    </body>
</html>